# Generated by Django 3.2.12 on 2022-02-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('objects_detected', models.CharField(max_length=1000)),
                ('timestamp', models.DateField()),
            ],
            options={
                'db_table': 'data',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='files')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'file',
            },
        ),
    ]
