# Generated by Django 3.2.12 on 2022-02-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='csv_file',
            field=models.FileField(upload_to=''),
        ),
    ]
